name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rahulssv/backend

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish-image:
    runs-on: ubuntu-20.04-ppc64le
    steps:
    - name: Checking Out Repository
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
        architecture: ppc64le
    - name: Fetching node modules
      run: |
        npm install
    - name: Build distributable
      run: |
          npm run build
      # npm run lint || true
        

    - name: Prepare Production-Only node_modules
      run: |
        rm -rf node_modules
        npm install --omit=dev

    # - name: Docker Set up QEMU
    #   uses: docker/setup-qemu-action@v3.0.0

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Extract Metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Log in to the Container Registry
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' }}
        platforms: >
            linux/ppc64le 
        #,
            # linux/arm64/v8,
            # linux/arm/v6,linux/arm/v7,
            # linux/ppc64le,
            # linux/s390x
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
